package model

type KugouSearchModel struct {
	Status  int `json:"status"`
	Errcode int `json:"errcode"`
	Data    struct {
		Timestamp       int    `json:"timestamp"`
		Tab             string `json:"tab"`
		Forcecorrection int    `json:"forcecorrection"`
		Correctiontype  int    `json:"correctiontype"`
		Total           int    `json:"total"`
		Istag           int    `json:"istag"`
		Allowerr        int    `json:"allowerr"`
		Info            []struct {
			Hash              string `json:"hash"`
			Sqfilesize        int    `json:"sqfilesize"`
			Sourceid          int    `json:"sourceid"`
			PayTypeSq         int    `json:"pay_type_sq"`
			Bitrate           int    `json:"bitrate"`
			Ownercount        int    `json:"ownercount"`
			PkgPriceSq        int    `json:"pkg_price_sq"`
			Songname          string `json:"songname"`
			AlbumName         string `json:"album_name"`
			SongnameOriginal  string `json:"songname_original"`
			Accompany         int    `json:"Accompany"`
			Sqhash            string `json:"sqhash"`
			FailProcess       int    `json:"fail_process"`
			PayType           int    `json:"pay_type"`
			RpType            string `json:"rp_type"`
			AlbumId           string `json:"album_id"`
			OthernameOriginal string `json:"othername_original"`
			Mvhash            string `json:"mvhash"`
			Extname           string `json:"extname"`
			Group             []struct {
				Hash              string `json:"hash"`
				Sqfilesize        int    `json:"sqfilesize"`
				Sourceid          int    `json:"sourceid"`
				PayTypeSq         int    `json:"pay_type_sq"`
				Bitrate           int    `json:"bitrate"`
				Ownercount        int    `json:"ownercount"`
				PkgPriceSq        int    `json:"pkg_price_sq"`
				Songname          string `json:"songname"`
				AlbumName         string `json:"album_name"`
				SongnameOriginal  string `json:"songname_original"`
				Accompany         int    `json:"Accompany"`
				Sqhash            string `json:"sqhash"`
				FailProcess       int    `json:"fail_process"`
				PayType           int    `json:"pay_type"`
				RpType            string `json:"rp_type"`
				AlbumId           string `json:"album_id"`
				OthernameOriginal string `json:"othername_original"`
				Mvhash            string `json:"mvhash"`
				Extname           string `json:"extname"`
				Price320          int    `json:"price_320"`
				Hash1             string `json:"320hash"`
				Topic             string `json:"topic"`
				Othername         string `json:"othername"`
				Isnew             int    `json:"isnew"`
				FoldType          int    `json:"fold_type"`
				OldCpy            int    `json:"old_cpy"`
				Srctype           int    `json:"srctype"`
				Singername        string `json:"singername"`
				AlbumAudioId      int    `json:"album_audio_id"`
				Duration          int    `json:"duration"`
				Filesize          int    `json:"320filesize"`
				PkgPrice320       int    `json:"pkg_price_320"`
				AudioId           int    `json:"audio_id"`
				Feetype           int    `json:"feetype"`
				Price             int    `json:"price"`
				Filename          string `json:"filename"`
				Source            string `json:"source"`
				PriceSq           int    `json:"price_sq"`
				FailProcess320    int    `json:"fail_process_320"`
				TransParam        struct {
					PayBlockTpl int `json:"pay_block_tpl"`
					Classmap    struct {
						Attr0 int `json:"attr0"`
					} `json:"classmap"`
					Qualitymap struct {
						Attr0 int `json:"attr0"`
					} `json:"qualitymap"`
					Cid   int `json:"cid"`
					Ipmap struct {
						Attr0 int `json:"attr0"`
					} `json:"ipmap"`
					CpyAttr0         int    `json:"cpy_attr0"`
					SongnameSuffix   string `json:"songname_suffix"`
					Language         string `json:"language"`
					MusicpackAdvance int    `json:"musicpack_advance"`
					Display          int    `json:"display"`
					DisplayRate      int    `json:"display_rate"`
				} `json:"trans_param"`
				PkgPrice      int    `json:"pkg_price"`
				PayType320    int    `json:"pay_type_320"`
				TopicUrl      string `json:"topic_url"`
				M4Afilesize   int    `json:"m4afilesize"`
				RpPublish     int    `json:"rp_publish"`
				Privilege     int    `json:"privilege"`
				Filesize1     int    `json:"filesize"`
				Isoriginal    int    `json:"isoriginal"`
				Privilege1    int    `json:"320privilege"`
				Sqprivilege   int    `json:"sqprivilege"`
				FailProcessSq int    `json:"fail_process_sq"`
			} `json:"group"`
			Price320       int    `json:"price_320"`
			Hash1          string `json:"320hash"`
			Topic          string `json:"topic"`
			Othername      string `json:"othername"`
			Isnew          int    `json:"isnew"`
			FoldType       int    `json:"fold_type"`
			OldCpy         int    `json:"old_cpy"`
			Srctype        int    `json:"srctype"`
			Singername     string `json:"singername"`
			AlbumAudioId   int    `json:"album_audio_id"`
			Duration       int    `json:"duration"`
			Filesize       int    `json:"320filesize"`
			PkgPrice320    int    `json:"pkg_price_320"`
			AudioId        int    `json:"audio_id"`
			Feetype        int    `json:"feetype"`
			Price          int    `json:"price"`
			Filename       string `json:"filename"`
			Source         string `json:"source"`
			PriceSq        int    `json:"price_sq"`
			FailProcess320 int    `json:"fail_process_320"`
			TransParam     struct {
				CpyGrade int `json:"cpy_grade,omitempty"`
				Classmap struct {
					Attr0 int `json:"attr0"`
				} `json:"classmap"`
				Language         string `json:"language"`
				CpyAttr0         int    `json:"cpy_attr0"`
				MusicpackAdvance int    `json:"musicpack_advance"`
				Ogg128Filesize   int    `json:"ogg_128_filesize,omitempty"`
				DisplayRate      int    `json:"display_rate"`
				CpyLevel         int    `json:"cpy_level,omitempty"`
				Qualitymap       struct {
					Attr0 int `json:"attr0"`
				} `json:"qualitymap"`
				PayBlockTpl    int    `json:"pay_block_tpl"`
				HashMultitrack string `json:"hash_multitrack,omitempty"`
				Cid            int    `json:"cid"`
				Ogg128Hash     string `json:"ogg_128_hash,omitempty"`
				Display        int    `json:"display"`
				Ipmap          struct {
					Attr0 int `json:"attr0"`
				} `json:"ipmap,omitempty"`
				HashOffset struct {
					ClipHash   string `json:"clip_hash"`
					StartByte  int    `json:"start_byte"`
					EndMs      int    `json:"end_ms"`
					EndByte    int    `json:"end_byte"`
					FileType   int    `json:"file_type"`
					StartMs    int    `json:"start_ms"`
					OffsetHash string `json:"offset_hash"`
				} `json:"hash_offset,omitempty"`
				AppidBlock     string `json:"appid_block,omitempty"`
				Ogg320Hash     string `json:"ogg_320_hash,omitempty"`
				Ogg320Filesize int    `json:"ogg_320_filesize,omitempty"`
				SongnameSuffix string `json:"songname_suffix,omitempty"`
			} `json:"trans_param"`
			PkgPrice      int    `json:"pkg_price"`
			PayType320    int    `json:"pay_type_320"`
			TopicUrl      string `json:"topic_url"`
			M4Afilesize   int    `json:"m4afilesize"`
			RpPublish     int    `json:"rp_publish"`
			Privilege     int    `json:"privilege"`
			Filesize1     int    `json:"filesize"`
			Isoriginal    int    `json:"isoriginal"`
			Privilege1    int    `json:"320privilege"`
			Sqprivilege   int    `json:"sqprivilege"`
			FailProcessSq int    `json:"fail_process_sq"`
		} `json:"info"`
		Aggregation   []interface{} `json:"aggregation"`
		Correctiontip string        `json:"correctiontip"`
		Istagresult   int           `json:"istagresult"`
	} `json:"data"`
	Error string `json:"error"`
}
